config/routes.rb
Rails.application.routes.draw do
  resources :file_shares

   root 'file_shares#index'

  match 'get-presigned', :to => 'file_shares#create_presigned', :via => :post

end

app/models/file_share.rb
class FileShare < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/file_shares_controller.rb
class FileSharesController < ApplicationController
  before_action :set_file_share, only: [:show, :edit, :update, :destroy]
  before_action :set_s3_direct_post, only: [:new, :edit, :create, :update]

  # GET /file_shares
  # GET /file_shares.json
  def index
    @file_shares = FileShare.all
  end

  # GET /file_shares/1
  # GET /file_shares/1.json
  def show
  end

  # GET /file_shares/new
  def new
    @file_share = FileShare.new
  end

  # GET /file_shares/1/edit
  def edit
  end
  
  def create_presigned
    url = PRESIGNER.presigned_url(:get_object, bucket: S3BUCKET, key: params[:key], expires_in: 3600);
    render text: url;
  end

  # POST /file_shares
  # POST /file_shares.json
  def create
    @file_share = FileShare.new(file_share_params)

    respond_to do |format|
      if @file_share.save
        flash[:success] = 'File share was successfully created.'
        format.html { redirect_to @file_share }
        format.json { render :show, status: :created, location: @file_share }
      else
        flash[:danger] = 'There was a problem creating the file share'
        format.html { render :new }
        format.json { render json: @file_share.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /file_shares/1
  # PATCH/PUT /file_shares/1.json
  def update
    respond_to do |format|
      if @file_share.update(file_share_params)
        flash[:success] = 'File share was successfully updated'
        format.html { redirect_to @file_share }
        format.json { render :show, status: :ok, location: @file_share }
      else
        flash[:danger] = 'There was a problem creating the file share'
        format.html { render :edit }
        format.json { render json: @file_share.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /file_shares/1
  # DELETE /file_shares/1.json
  def destroy
    @file_share.destroy
    respond_to do |format|
      
        flash[:success] = 'File share was successfully destoryed'
        format.html { redirect_to @file_share }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_file_share
      @file_share = FileShare.find(params[:id])
    end

    #setup function to allow users to direct post to s3 bucket
    def set_s3_direct_post
      @s3_direct_post = S3_BUCKET.presigned_post(key: "uploads/#{SecureRandom.uuid}/${filename}", success_action_status: '201', acl: 'authenticated-read')
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def file_share_params
      params.require(:file_share).permit(:user, :file_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/file_shares_helper.rb
module FileSharesHelper
end

app/views/file_shares/_form.html.erb
<%= form_for(@file_share, html: { class: 'directUpload', data: { 'form-data' => (@s3_direct_post.fields), 'url' => @s3_direct_post.url, 'host' => URI.parse(@s3_direct_post.url).host } }) do |f| %>
  <% if @file_share.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@file_share.errors.count, "error") %> prohibited this file_share from being saved:</h2>

      <ul>
      <% @file_share.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :user, class: 'col-sm-2 control label'  %>
    <div class="col-sm-10">
      <%= f.text_field :user %>
    </div>
  </div>
  <div class="field form-group">
    <%= f.label :file_url, class: 'col-sm-2 control-label' %>
     <div class="col-sm-10">
        <%= f.file_field :file_url, class: 'form-control' %>
     </div>
  </div>
  <div class="actions form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit %>
    </div>
  </div>
<% end %>

app/views/file_shares/edit.html.erb
<h1>Editing File Share</h1>

<%= render 'form' %>

<%= link_to 'Show', @file_share %> |
<%= link_to 'Back', file_shares_path %>

app/views/file_shares/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing File Shares</h1>

<table class="table" >
  <thead>
    <tr>
      <th>User</th>
      <th>File url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @file_shares.each do |file_share| %>
      <tr>
        <td ><%= file_share.user %></td>
        <td ><a href="<%= file_share.file_url %>"><%= file_share.file_url %></a></td>
        <td ><%= link_to 'Delete', file_share, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New File share', new_file_share_path %>

app/views/file_shares/new.html.erb
<h1>Upload File</h1>

<%= render 'form' %>

<%= link_to 'Back', file_shares_path %>

app/views/file_shares/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @file_share.user %>
</p>

<p>
  <strong>File url:</strong>
  <%= @file_share.file_url %>
</p>

<%= link_to 'Edit', edit_file_share_path(@file_share) %> |
<%= link_to 'Back', file_shares_path %>

app/views/layouts/application.html.erb
<!-- app/views/layouts/application.html.erb -->

<!DOCTYPE html>
<html>
  <head>
    <title>DirectS3Dropbox</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'shared/navigation' %>
    <div id="main-container" class="container">
      <div class="row">
        <div class="col-xs-12">
          <% flash.each do |name, msg| -%>
            <%= content_tag :div, msg, class: "alert alert-#{name}" %>
          <% end -%>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-9">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/shared/_navigation.html.erb
<!-- app/views/shared/_navigation.html.erb -->

<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">S3 Dropbox</a>
    </div>
  </div>
</nav>